### ISSUE TITLE
Weird values in hovertext for Confirmed cases/tests

### ISSUE THREAD

**Issue by bildanderwand** [covid-19-Re/shiny-dailyRe#11]
I think there is something wrong with the values in the hovertext for Confirmed cases/tests. See the uploaded picture.

![Bildschirmfoto von 2020-09-19 14-44-24](https://user-images.githubusercontent.com/68001466/93667578-63cb0580-fa87-11ea-99b2-85cc720e89af.png)

**Comment by dcangst** [comment]
thank you very much for the heads up!
I temporarily removed the clearly wrong data from the website and will fix the bug asap.

**Comment by dcangst** [comment]
I fixed the issue. thanks again for letting us know
