### ISSUE TITLE
>3 Countries Selection Issues

### ISSUE THREAD

**Issue by TrevorWinstral** [covid-19-Re/shiny-dailyRe#17]
When selecting more than 3 countries, I am unable to click or scroll with the 3 dots to see the R_e for more than the first 3 countries. I assumed that the 3 dots implied that there was some sort of gallery or carousel feature and not just that there was more info that couldn't be displayed. If this is a feature not a bug, then my bad for misinterpreting.

**Comment by dcangst** [comment]
Thank you for your report. However, I don't think I understand. Where do you see the 3 dots?

**Comment by dcangst** [comment]
Ok I get it now! sorry! I can see how that is confusing!

**Comment by dcangst** [comment]
The three dots are meant to indicate that not all data is shown. I will try to think of a better way to either show all data or a better indicator

**Comment by dcangst** [comment]
I changed the three dots to be a button to show/hide the additional Re values. What do you think? Does that make more sense?
