### ISSUE TITLE
Allow comparison for data types missing for some countries 

### ISSUE THREAD

**Issue by jscire** [covid-19-Re/shiny-dailyRe#19]
When selecting multiple countries, the list of data types that can be compared is only comprised of data types shared by all countries. This is a minor inconvenience that becomes problematic when looking at swiss cantons. As it is now, we cannot exclude deaths or hospital admissions from cantons with very low counts, because otherwise we cannot look at these traces for any canton (except when selecting individual cantons).

The solution I think would be to allow the comparison for all data types all the time, or for the all the data types that are at least included once in the compared data.

**Comment by dcangst** [comment]
fixed in e79a25316d94cf655eec87c8a18f065b0afc2560
