### ISSUE TITLE
Tracking der Maßnahmen auf Regionaler ebene (pro Kanton)

### ISSUE THREAD

**Issue by Schwefelhard** [covid-19-Re/shiny-dailyRe#20]
Hallo Team,

Um die Wirksamkeit einzelner Maßnahmen oder zumindest Maßnahmenpakete besser untersuchen zu können, wäre es toll diese auch pro Kanton aufzuführen (die kantonalen Maßnahmen ja oft bereits vor denen des Bundes eingeführt).

These:
Wenn die Maßnahmen Pakete tatsächlich dazu beitragen eine Überlastung der Spitäler vorzubeugen, müsste das doch auch statistisch nachweisbar sein (Korrelation zwischen Maßnahmen und Infektionsgeschehen bzw. Re)

Im Optimal fall könnten Gruppen mit bestimmten Massnahmen und solche ohne verglichen werden

Mit freundlichen Grüssen

Fabian Adam

**Comment by Schwefelhard** [comment]
thanks for adding the label

**Comment by dcangst** [comment]
We now display (and use for step wise Re estimation) the Stringency Index for the individual cantons as calculated by the Konjunkturforschungsstelle of ETH Zurich https://github.com/KOF-ch/economic-monitoring.

**Comment by Schwefelhard** [comment]
Awesome, fantastic job, love It!

If we only could distinguish between cases with and because of covid... somehow wired that BAG is still not able to provide us with more differentiated data.

**Comment by dcangst** [comment]
The dashbord only shows confirmed Covid cases, deaths and hospitalizations.

**Comment by Schwefelhard** [comment]
sure I know, more differentiated data is not available....
