### ISSUE TITLE
CSV Timeseries or HTML Table

### ISSUE THREAD

**Issue by pick2510** [covid-19-Re/shiny-dailyRe#22]
Dear Development Team,

Maybe I didn‘t find on the app website, but can you provide a better way to access the time series. Clicking through the plot is not really efficient and your calculations just got much more important in CH policy making.

Suggestion:
Either downloadable timeseries as csv or classical html table on the app website.

**Comment by dcangst** [comment]
All data is available at https://github.com/covid-19-Re/dailyRe-Data

**Comment by dcangst** [comment]
Direkter Link zu den aktuellsten Schätzungen für die Schweiz: https://raw.githubusercontent.com/covid-19-Re/dailyRe-Data/master/CHE-estimates.csv

**Comment by pick2510** [comment]
I see. Thanks. 
But I think my original point is still valid: 
It should be easier for the public and decision makers to see the  R_e(t, canton). In the COVID-19 Verordnungserläuterungen the link to web app is directly in the text. Instead of activating and deactivating legend entries, there should be an easier way to get cantonal data.

**Comment by dcangst** [comment]
We are acutely aware that the link is in the COVID-19 Verordnungserläuterungen. Unfortunately, this came as a surprise to us.

for the moment this easy script should help:

```r
library(tidyverse)

reSchweiz <- read_csv(
  file = "https://raw.githubusercontent.com/covid-19-Re/dailyRe-Data/master/CHE-estimates.csv"
)

# Re aufgrund von bestätigten Fällen in den letzten 7 tagen im Kanton `canton`
canton <- "SG"

reSchweiz %>%
  filter(
    region == canton,
    data_type == "Confirmed cases",
    estimate_type == "Cori_slidingWindow",
    date > max(date) - 7
)
```

**Comment by dcangst** [comment]
afaik filtering tables is also straightforward in Excel

**Comment by pick2510** [comment]
Perfect. 
I think this should be as transparent and easily accessible as possible. There may be lots of discussion relating the defined tresholds in the coming weeks/months. Since you‘re now the official source, this is even more important.
