### ISSUE TITLE
all_delays.csv missing in repo

### ISSUE THREAD

**Issue by david125125** [covid-19-Re/shiny-dailyRe#23]
https://github.com/covid-19-Re/shiny-dailyRe/blob/7f772c764f8ec8c4f76704a62880d4ccb7ed626d/app/otherScripts/ReCountry.R#L178

Can you maybe add the file "all_delays.csv" to the repo?

**Comment by dcangst** [comment]
`all_delays.csv` is created by `format_linelist_data.R`. Unfortunately we're not able to share the data for Switzerland, but you can create the file from DEU and HKG data by removing CHE here:
https://github.com/covid-19-Re/shiny-dailyRe/blob/7f772c764f8ec8c4f76704a62880d4ccb7ed626d/app/otherScripts/format_linelist_data.R#L13

**Comment by david125125** [comment]
Thanks!
