### ISSUE TITLE
Different ”most recent possible Re estimate”

### ISSUE THREAD

**Issue by palrogg** [covid-19-Re/shiny-dailyRe#5]
[Situation report](https://ncs-tf.ch/en/situation-report) shows Re=2.36 on June 22 as “most recent possible Re estimate”:
![Capture d’écran 2020-07-06 à 17 42 34](https://user-images.githubusercontent.com/12730304/86612359-4de19480-bfb0-11ea-8539-5b068c0172b4.png)

Same values can be found in the file download section and Switzerland seems to have much higher values than selected European regions (20200706-ReEstimatesEU.csv).
![Capture d’écran 2020-07-06 à 17 53 09](https://user-images.githubusercontent.com/12730304/86613320-b67d4100-bfb1-11ea-8aa6-258d0e66df07.png)

But https://ibz-shiny.ethz.ch/covid-19-re/ shows more recent, and different, values such as 1.95 for Switzerland on June 26:
![Capture d’écran 2020-07-06 à 17 44 19](https://user-images.githubusercontent.com/12730304/86612672-c8121900-bfb0-11ea-8ddb-5c9ce1fa15d4.png)

Could there be an inconsistency / missing data update?

Best

**Comment by dcangst** [comment]
Thank you for your feedback. The plot on ncs-tf.ch is fetched directly from https://ibz-shiny.ethz.ch/covid-19-re/. It is possible that the ncs-tf.ch page shows new data with a little delay. Please empty your caches and reload ncs-tf.ch for the updated plots.
