### ISSUE TITLE
Data not accessible

### ISSUE THREAD

**Issue by daenuprobst** [covid-19-Re/shiny-dailyRe#6]
The app / scripts require data from an ETHZ owncloud instance to be downloaded (https://polybox.ethz.ch/remote.php/webdav/BAG%20COVID19%20Data); however, this requires a user / password. Is there an anonymous account or could the data be provided publicly by other means?

**Comment by dcangst** [comment]
Unfortunately this data is not publicly available as the data is not publicly shared by the Federal Office of Public Health. I am aware that at the moment the scripts do not work without access to this data.

If you have access to the data shared by the BAG (e.g. through the Scientific Taskforce or via SSPH) you can workaround this issue by placing (or symlinking etc.) the files (as named by the FOPH) into the app/data/BAG directory.

The reason we use this data is that it contains information on symptom onset and hospitalization which we use to estimate the distribution of delays for the deconvolution.

**Comment by dcangst** [comment]
another issue is the private repository we used to use to sync other not publicly available data and some other stuff. This is largely deprecated and I will remove this soon.

**Comment by daenuprobst** [comment]
Thank you for clarifying.
