### ISSUE TITLE
Value labels for 7-day averages are incorrect

### ISSUE THREAD

**Issue by simon-d-s** [covid-19-Re/shiny-dailyRe#8]
In 7-day average mode for daily cases, value labels shown on "mouse-over" still show daily (not averaged) numbers. This is confusing, because the label explicitly declares the shown number as "7 day average", which is obviously not the case when comparing it to the height of the bar. In the example below, the number in the label should read something like 90 cases and not 128:

![grafik](https://user-images.githubusercontent.com/6119342/89996845-98c78980-dc8b-11ea-916f-ee09cc386708.png)

**Comment by simon-d-s** [comment]
I was too slow, issue can be merged with #7.

**Comment by dcangst** [comment]
Thank you for the report! i fixed the bug in commit 2a61a2b88ddbf4092b8499376098ced5f75b78db
