### ISSUE TITLE
Daily data not updated anymore

### ISSUE THREAD

**Issue by mathias-lutz** [covid-19-Re/shiny-dailyRe#9]
Daily Re for select countries hasn't been updated for the last 5 days.
https://github.com/covid-19-Re/dailyRe-Data

The linechart for Switzerland shows more uptodate data:
https://ibz-shiny.ethz.ch/covid-19-re/

Thanks for providing the corresponding raw data again!

**Comment by dcangst** [comment]
I am very sorry for this regression! I failed to include those changes in the new redesign. Swiss data is being updated now and will be committed to the data repository shortly. Other countries will follow when the next update is run.

**Comment by dcangst** [comment]
all estimates have been updated.

**Comment by mathias-lutz** [comment]
Looks like the data doesn't get updated.
Again the linechart for Switzerland shows more uptodate data, than the CSV.
https://ibz-shiny.ethz.ch/covid-19-re/

**Comment by dcangst** [comment]
ich bin nicht sicher ob ich das richtig verstehe: die neuste Schätzung auf der Webseite und in den Daten ist vom 28.8.

**Comment by dcangst** [comment]
ich habe eben die routine nochmals laufen gelassen und es hat alles geklappt, d.h. das neue Datenfile wurde auf das Repo hochgeladen.

**Comment by dcangst** [comment]
Haben Sie evtl. screenshots vom problem? d.h. welche daten zu welchem Zeitpunkt nicht richtig waren?

**Comment by mathias-lutz** [comment]
Bis vor ca. einer Woche konnten wir die aktuellen Daten für die Schweiz stets als CSV runterladen. Die Werte stimmten mit der Grafik auf ihrer Webseite überein. Dann wurde das CSV plötzlich nicht mehr aktualisiert, worauf hin ich mich hier nach fünf Tagen gemeldet habe. Nun sind die neusten Werte im CSV auf den 28. August datiert, während die Grafik bereits Werte bis zum 29. zeigt (siehe Screenshot). Wir wären froh, wenn wir wieder täglich die Werte, welche in der Grafik abgebildet sind, via CSV beziehen könnten.

![che-estimates](https://user-images.githubusercontent.com/37148144/92564897-30fc6280-f27a-11ea-9d11-fafb3bf0737f.jpg)

**Comment by mathias-lutz** [comment]
Oh, habe gerade bemerkt, dass ich die Linie der Tests angeschaut habe, anstatt der Confirmed Cases. Sorry!
Trotzdem: Wir hatten die Daten am 07.09. übernommen, diese zeigten den neusten Wert für den 28.08., heute ist der letzte Wert immer noch auf den 28. datiert. Lief das Update korrekt? Früher wurden die Daten doch im Tagesrhythmus erweitert, oder?

**Comment by dcangst** [comment]
Gestern bekamen wir leider keine neuen Daten.

**Comment by dcangst** [comment]
Die Daten von gestern sind jetzt gekommen. Das Update lief automatisch und die Daten wurden hochgeladen. So wie ich das sehe läuft auf technischer ebene alles problemlos. Ich werde die Situation trotzdem weiterhin beobachten.
